import { readdir } from "node:fs/promises";
import { extname, join, relative } from "node:path";

const IGNORED_DIRECTORIES = new Set([
  ".git",
  ".next",
  ".react-email",
  ".turbo",
  ".vercel",
  "build",
  "coverage",
  "dist",
  "node_modules",
  "out",
  "storybook-static",
]);

const BINARY_EXTENSIONS = new Set([
  ".gif",
  ".ico",
  ".jpeg",
  ".jpg",
  ".mp4",
  ".otf",
  ".pdf",
  ".png",
  ".ttf",
  ".webm",
  ".webp",
  ".woff",
  ".woff2",
  ".zip",
]);

// Lockfiles never contain placeholders and are regenerated by `bun install`.
const IGNORED_FILES = new Set(["bun.lock", "bun.lockb", "package-lock.json"]);

/** Every text file in the repository, as paths relative to `root`. */
export const listTextFiles = async (root: string): Promise<string[]> => {
  const files: string[] = [];

  const walk = async (directory: string) => {
    const entries = await readdir(directory, { withFileTypes: true });

    for (const entry of entries) {
      const path = join(directory, entry.name);

      if (entry.isDirectory()) {
        if (!IGNORED_DIRECTORIES.has(entry.name)) {
          // biome-ignore lint/performance/noAwaitInLoops: depth-first walk keeps memory flat
          await walk(path);
        }
      } else if (
        entry.isFile() &&
        !IGNORED_FILES.has(entry.name) &&
        !BINARY_EXTENSIONS.has(extname(entry.name).toLowerCase())
      ) {
        files.push(relative(root, path));
      }
    }
  };

  await walk(root);

  return files.sort();
};
